import Head from 'next/head'
import Sidebar from '../../components/Sidebar'
import Widgets from '../../components/Widgets'
import CommentModal from '../../components/CommentModal'
import { ArrowLeftIcon } from '@heroicons/react/24/solid'
import { useRouter } from 'next/router'
import Post from '../../components/Post'
import { collection, doc, onSnapshot, orderBy, query } from 'firebase/firestore'
import { db } from '../../firebase'
import { useEffect, useState } from 'react'
import Comment from '../../components/Comment'

export default function PostPage({ newsResults, randomUserList }) {
  const router = useRouter()
  const { id } = router.query
  const [post, setPost] = useState()
  const [comments, setComments] = useState([])

  //get post data
  useEffect(() => {
    onSnapshot(doc(db, 'posts', id), (snapshot) => {
      setPost(snapshot)
    })
  }, [db, id])

  //get all comments for specific post
  useEffect(() => {
    onSnapshot(
      query(
        collection(db, 'posts', id, 'comments'),
        orderBy('timestamp', 'desc')
      ),
      (snapshot) => setComments(snapshot.docs)
    )
  }, [])

  return (
    <div>
      <Head>
        <title>Post Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex min-h-screen mx-auto'>
        {/* Sidebar */}
        <Sidebar />
        {/* Feed */}

        <div className='xl:ml-[370px] border-l border-r xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-xl border-gray-200'>
          <div className='flex py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200 items-center space-x-2'>
            <div className='hoverEffect' onClick={() => router.push('/')}>
              <ArrowLeftIcon className='h-5' />
            </div>
            <h2 className='text-lg sm:text-xl font-bold cursor-pointer'>
              Tweet
            </h2>
          </div>
          <Post id={id} post={post} />
          {comments.length > 0 &&
            comments.map((comment) => (
              <Comment
                key={comment.id}
                id={comment.id}
                comment={comment.data()}
              />
            ))}
        </div>

        {/* Widgets */}
        <Widgets
          newsResults={newsResults.articles}
          randomUserList={randomUserList.results}
        />
        {/* Modal */}
        <CommentModal />
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const newsResults = await fetch(
    `https://newsapi.org/v2/top-headlines?country=us&apiKey=${process.env.NEWS_API_KEY}`
  ).then((res) => res.json())

  const randomUserList = await fetch(
    'https://randomuser.me/api/?results=30&inc=name,login,picture'
  ).then((res) => res.json())

  return {
    props: { newsResults, randomUserList },
  }
}
